//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyAppApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildingInventory
    {
        public int Id { get; set; }
        public string BuildingType { get; set; }
        public string BuildingUse { get; set; }
        public string BuildingName { get; set; }
        public Nullable<double> BuildingLength { get; set; }
        public Nullable<double> BuildingWidth { get; set; }
        public Nullable<int> NumberOfFloor { get; set; }
        public string ImageName { get; set; }
        public string ImagePath { get; set; }
    }
}
