//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyAppApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoadInventory
    {
        public int Id { get; set; }
        public string RoadOwner_ { get; set; }
        public string RoadType { get; set; }
        public string RoadName { get; set; }
        public Nullable<double> RoadLength { get; set; }
        public Nullable<double> RoadWidth { get; set; }
        public Nullable<int> NumberOfLane { get; set; }
        public string ImageName { get; set; }
        public string ImagePath { get; set; }
    }
}
