//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyAppApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SurveyAppDBEntities : DbContext
    {
        public SurveyAppDBEntities()
            : base("name=SurveyAppDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BuildingInventory> BuildingInventories { get; set; }
        public DbSet<RoadInventory> RoadInventories { get; set; }
        public DbSet<UserTable> UserTables { get; set; }
    }
}
